### ISSUE TITLE
Remove hacky parentdir directory imports in starters

### ISSUE THREAD

**Issue by gnott** [elifesciences/elife-bot#991]
As described in https://github.com/elifesciences/elife-bot/pull/990#discussion_r358311879, there are still some old hacky ways to import parent directories in starter code. The object is to test whether or why these are required, and if they are still required, refactor it so they can import what they need properly in a normal way.

# DoD:

- [x] No more `os.path.dirname(os.path.dirname(...` style imports required

# Tasks / plan

- [x] Remove all the weird imports
- [x] Test it on `end2end` testing - revert the PR if it fails testing
- [x] Debug further (if it failed) and add more todo tasks to fix it

**Comment by gnott** [comment]
A note about some old memories about why this import line may be present.

**Possible reason 1**
There was a time early on where what was the `elife-tools` code existed in a folder that was a folder at the same level as the `elife-bot` folder. In order to import it (because `elife-tools` was not a pip-instalable module) some parts needed to also import from above the `elife-bot` folder.

**Possible reason 2**
Another possible reason is for the dynamic loading of activity objects. I think this was more likely happening in the `worker.py`, which no longer uses this parent directory import mess. It was because when the module name to dynamically import was concatenated, it needed to resolve the module name into folder names.

**Possible reason 3**
It's possible in Python 2 it was hard to do a relative import of a module, which is no longer a problem with Python 3

**Possible reason 4**
It could be that early on some key folders did not have a `__init__.py` file to make it possible to import from them easily.

If these imports solved one of these four reasons at some time in the past, they probably no longer apply, and we'll have no headaches in removing these weird imports. The one place that may matter is in the dynamic importing of modules, and if we run into that, then we can improve the code to make it work more clearly.

**Comment by gnott** [comment]
After testing the latest merged PR experiment, I think the problem is somewhat related to the above reasons but slightly different.

I was able to execute a `SilentCorrectionsIngest` workflow fine as a result of adding a zip file to the S3 bucket.

The probably happens when I tested the starter for `PubmedArticleDeposit` locally.

If I am in `elife-bot` folder and I try to execute:

```
python starter_PubmedArticleDeposit.py -e dev
```

I get

```
Traceback (most recent call last):
  File "starter/starter_PubmedArticleDeposit.py", line 8, in <module>
    import log
ImportError: No module named 'log'
```

My understanding so far is, if a starter is run as a script, then the "package" structure will begin at `starter/`, and so it is unable to import `log.py` from the root directory of the project.

I tried some relative import syntax to try and import it but it didn't work.

I thought we could move `log.py` to `provider/log.py` for easier importing, but when a starter is run as a script, it can also not import from the `provider/` folder.

This is a reason why adding the parent directory to the absolute path of the starter script has helped, and it fits with many StackOverflow pages that say the same.

There is probably a solution to this, I just don't have it right now. @giorgiosironi, do you have suggestions how these starters can work as importable modules as well as executable scripts?

**Comment by giorgiosironi** [comment]
Isn't this a `PYTHONPATH` issue? I've used this before in other projects:
```
PYTHONPATH=. AWS_DEFAULT_REGION=us-east-1 python econtools/econ_article_feeder.py -p elife-50731-vor-r1 -r 1 elife-production-final workflow-starter-queue InitialArticleZip
```
That should force the package structure to start in the current directory even if the script is inside an arbitrary subfolder. Try it out and let me know.

**Comment by gnott** [comment]
`PYTHONPATH` works for me, thanks @giorgiosironi! I think I'll make a note about this in the project readme, because I'm liable to forget how to run the starters otherwise.

**Comment by gnott** [comment]
There remains only one place this parent directory import is used, in https://github.com/elifesciences/elife-bot/blob/develop/tests/__init__.py where it helps to locate test fixtures. It may or may not still be required, but probably doesn't do too much harm.
