### ISSUE TITLE
Refactor and standardise workflow starters

### ISSUE THREAD

**Issue by gnott** [elifesciences/elife-bot#992]
As mentioned in https://github.com/elifesciences/elife-bot/pull/990#discussion_r358312510, there is similar code across many different starter modules, indicating a strong possibility there could be simpler and reusable ways to call a starter.

# DoD

- [x] Less code duplication across all the starter module code
- [x] More standardised list of starter parameters (if possible)
- [x] Clearer and more standard way to gather starter data (such as bucket object lists or other data sources used in starters)

# Tasks

- [x] Do a survey of all the starters, their parameters and logic, looking for similarities and differences
- [x] Move logic to a base starter object or to some starter helper libraries or functions that can be reused across all starters
- [x] Starter object (to be created) accepts a `logger` to be passed to it
- [x] Remove any starter code that is no longer in use
- [x] Aim to reduce the amount of code and complexity of code used in all the starters, so they are easier to understand
- [x] Use `ArgumentParser` instead of `OptionParser` for console start logic, and if possible standarise the parsing of arguments into `provider/utils.py`
- [x] Can probably use `helper.get_starter_logger()` everywhere for logging
- [x] Improve the test coverage or test scenarios

# Starter module list for tracking progress

- [x] starter/cron_FiveMinute.py
- [x] starter/cron_NewS3POA.py
- [x] starter/objects.py
- [x] starter/starter_AdminEmail.py
- [x] starter/starter_ApproveArticlePublication.py
- [x] starter/starter_CopyGlencoeStillImages.py
- [x] starter/starter_DepositCrossref.py
- [x] starter/starter_DepositCrossrefPeerReview.py
- [x] starter/starter_DepositDOAJ.py
- [x] starter/starter_FTPArticle.py
- [x] starter/starter_IngestAcceptedSubmission.py
- [x] starter/starter_IngestArticleZip.py
- [x] starter/starter_IngestDecisionLetter.py
- [x] starter/starter_IngestDigest.py
- [x] ~starter/starter_InitialArticleZip.py~ removed in PR https://github.com/elifesciences/elife-bot/pull/1299
- [x] starter/starter_LensArticlePublish.py
- [x] starter/starter_PMCDeposit.py
- [x] starter/starter_PackagePOA.py
- [x] starter/starter_Ping.py
- [x] starter/starter_PostPerfectPublication.py
- [x] starter/starter_ProcessArticleZip.py
- [x] starter/starter_PubRouterDeposit.py
- [x] starter/starter_PublicationEmail.py
- [x] starter/starter_PublishPOA.py
- [x] starter/starter_PubmedArticleDeposit.py
- [x] starter/starter_SilentCorrectionsIngest.py
- [x] starter/starter_SilentCorrectionsProcess.py
- [x] starter/starter_SoftwareHeritageDeposit.py
- [x] starter/starter_helper.py

**Comment by gnott** [comment]
Added a list of the starter module names so progress can be tracked, and I was unsure how far this issue was progressed since last looking at it.

**Comment by gnott** [comment]
Final PR https://github.com/elifesciences/elife-bot/pull/1309 reduced more duplicate code and applied the formats across all the starter modules with linted code and increased test coverage, good enough to consider this round of refactoring completed.
